# This is the default dynamic plugins config, and any user configuration should be added dynamic-plugins.override.yaml instead
includes:
  - dynamic-plugins.default.yaml
  # Writable path in the init container for extensions plugin configuration.
  - /dynamic-plugins-root/dynamic-plugins.extensions.yaml

plugins:
  # Guest auth backend module — RHDH 2+ no longer bundles auth provider plugins statically (https://redhat.atlassian.net/browse/RHIDP-15348).
  # These will be available as dynamic plugins (https://redhat.atlassian.net/browse/RHIDP-16098)
  # TODO: update this if/when it is listed in the DPDY. Remove this if it comes enabled by default in the DPDY.
  - package: 'oci://ghcr.io/redhat-developer/rhdh-plugin-export-overlays/backstage-plugin-auth-backend-module-guest-provider:bs_1.52.0__0.2.20'
    enabled: true

  # Tech Radar frontend plugin
  - package: 'oci://quay.io/rhdh/backstage-community-plugin-tech-radar:{{inherit}}'
    enabled: true

  # Quay plugins
  - package: 'oci://ghcr.io/redhat-developer/rhdh-plugin-export-overlays/backstage-community-plugin-quay-backend:bs_1.52.0__1.17.0'
    enabled: true

  - package: 'oci://ghcr.io/redhat-developer/rhdh-plugin-export-overlays/backstage-community-plugin-quay:bs_1.52.0__1.37.1'
    enabled: true
    pluginConfig:
      dynamicPlugins:
        frontend:
          backstage-community.plugin-quay:
            mountPoints:
              - mountPoint: entity.page.image-registry/cards
                importName: QuayPage
                config:
                  layout:
                    gridColumn: 1 / -1
                  if:
                    anyOf:
                      - isQuayAvailable

  # Scaffolder Github plugin - used by Dynamic Plugin Software Templates
  - package: 'oci://quay.io/rhdh/backstage-plugin-scaffolder-backend-module-github:{{inherit}}'
    enabled: true

  #########################################################
  # Enable dynamic plugins installation by using Extensions
  #########################################################

  - package: 'ref://red-hat-developer-hub-backstage-plugin-extensions'
    enabled: true

  - package: 'ref://red-hat-developer-hub-backstage-plugin-extensions-backend-dynamic'
    enabled: true
    pluginConfig:
      extensions:
        installation:
          enabled: true
          saveToSingleFile:
            # NOTE: the path needs to be writable by the main RHDH container user
            file: /opt/app-root/src/dynamic-plugins-root/dynamic-plugins.extensions.yaml
  ########## End Extensions #################################

  #########################################################
  # Developer Lightspeed plugins
  #########################################################

  # Lightspeed frontend plugin
  # TODO: re-enable this once the catalog index is stabilized
  - package: 'oci://registry.access.redhat.com/rhdh/red-hat-developer-hub-backstage-plugin-lightspeed:{{inherit}}'
    enabled: false

  # Lightspeed backend plugin
  # TODO: re-enable this once the catalog index is stabilized
  - package: 'oci://registry.access.redhat.com/rhdh/red-hat-developer-hub-backstage-plugin-lightspeed-backend:{{inherit}}'
    enabled: false
