
includes:
  - dynamic-plugins.default.yaml

plugins:
  - package: "https://npm.registry.redhat.com/@redhat/backstage-plugin-orchestrator/-/backstage-plugin-orchestrator-1.8.10.tgz"
    integrity: sha512-Tlqs2s4WuzM0QQTvgpIxSj0YPA5Lhr0ahMrEXwu0NRnlehNjJjl6NCZObjKATftcOmYRzBlMaC4JMvTOWNFDlA==
    disabled: false
    pluginConfig:
      dynamicPlugins:
        frontend:
          red-hat-developer-hub.backstage-plugin-orchestrator:
            appIcons:
              - importName: OrchestratorIcon
                name: orchestratorIcon
            dynamicRoutes:
              - importName: OrchestratorPage
                menuItem:
                  icon: orchestratorIcon
                  text: Orchestrator
                path: /orchestrator
  - disabled: false
    package: "https://npm.registry.redhat.com/@redhat/backstage-plugin-orchestrator-backend-dynamic/-/backstage-plugin-orchestrator-backend-dynamic-1.8.10.tgz"
    integrity: sha512-dRozMLDbj7AYgX4StT53rQ7OqnSx7gn4Js4z/1eZoPAuFm1T/4zwjoOWGJxmmNNPH1pFpeopT8Kc3VVVsWrYeA==
    pluginConfig:
      orchestrator:
        dataIndexService:
          url: http://sonataflow:8899
  - disabled: false
    package: "https://npm.registry.redhat.com/@redhat/backstage-plugin-scaffolder-backend-module-orchestrator-dynamic/-/backstage-plugin-scaffolder-backend-module-orchestrator-dynamic-1.8.10.tgz"
    integrity: sha512-jwkwh4sK9jEjbxj6VH/Cr7BAu0nTN2BtLqmeGQWXHwX51U6Vt0hurYi1cHZyD2qPhDRFxZ3rUzWdbKlwNPAvjw==
    pluginConfig:
      orchestrator:
        dataIndexService:
          url: http://sonataflow:8899
  - disabled: false
    package: "https://npm.registry.redhat.com/@redhat/backstage-plugin-orchestrator-form-widgets/-/backstage-plugin-orchestrator-form-widgets-1.8.10.tgz"
    integrity: sha512-BGnPNkd2JZ8hIrkZ8+/C1RSH1PA7DT8SPqkV1MsrRRONYSJZ/xcVNFb2HWo3BtIjYV3pbASm+vysuBYyxilQog==
    pluginConfig:
      dynamicPlugins:
        frontend:
          red-hat-developer-hub.backstage-plugin-orchestrator-form-widgets: {}
