# This is an example override file for catalog components.
# If present, this file will be used instead of components.yaml.
# Uncomment and edit the entries below to override catalog components.

apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: example-service
  description: A simple demo component to appear in the Software Catalog.
  annotations:
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  lifecycle: experimental
  owner: user:default/user