services:
  install-dynamic-plugins:
    volumes:
      - ./developer-lightspeed/configs:/opt/app-root/src/developer-lightspeed/configs:Z
  rhdh:
    volumes:
      - ./developer-lightspeed/configs:/opt/app-root/src/developer-lightspeed/configs:Z
  ollama:
    image: docker.io/ollama/ollama:0.10.0-rc0
    container_name: ollama
    volumes:
      - ${OLLAMA_MODELS_PATH:-ollama_data}:/root/.ollama
    depends_on:
      rhdh:
        condition: service_started
    network_mode: "service:rhdh"
    command: >
      "ollama serve & sleep 5 && ollama pull ${OLLAMA_MODEL:-tinyllama} && touch /tmp/ready && wait"
    entrypoint: [ "sh", "-c" ]
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "test", "-f", "/tmp/ready" ]
      interval: 10s
      timeout: 5s
      retries: 5
  road-core-service:
    image: ${ROAD_CORE_IMAGE:-quay.io/redhat-ai-dev/road-core-service:rcs-06302025-rhdh-1.6} # dclint disable-line service-image-require-explicit-tag
    container_name: road-core-service
    depends_on:
      rhdh:
        condition: service_started
      ollama:
        condition: service_healthy
    volumes:
      - ./developer-lightspeed/configs:/opt/app-root/src/developer-lightspeed/configs:Z
    environment:
      - PROJECT=rhdh
      - RCS_CONFIG_FILE=/opt/app-root/src/developer-lightspeed/configs/extra-files/road-core-service-config.yaml
      - OPENAI_API_KEY=${LLM_SERVER_TOKEN}
      - RHDH_CONFIG_FILE=/opt/app-root/src/developer-lightspeed/configs/app-config/app-config.lightspeed.local.yaml
    env_file:
      - path: "./default.env"
        required: true
      - path: "./.env"
        required: false
    network_mode: "service:rhdh"
volumes:
  ollama_data:
